### ISSUE TITLE
Clear out terminal on each run

### ISSUE THREAD

**Issue by blakeherrington** [blakeherrington/vscode-ruby-test-launcher#4]
It's annoying to have to scroll to the bottom of each test run since it doesn't do this automatically. It's also difficult to tell the different test runs apart. It'd be better to clear things out.

**Comment by Brick-Mover** [comment]
Add `terminal.sendText('clear');` before
```terminal.sendText(`test_launcher ${launcher_args}`);``` seems to fix the issue. Not sure this is the best way to solve the problem though.
